import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "./provider";
import Header from "./components/ui/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider>
        <body className="w-screen h-screen flex flex-col items-center justify-start overflow-x-hidden">
          <Header />
          {children}
        </body>
      </Provider>
    </html>
  );
}
